server:
  port: 9080
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    showSql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher